# Generated by Django 3.1.7 on 2021-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('R', 'Red'), ('W', 'white'), ('B', 'Black')], max_length=100)),
            ],
        ),
    ]
