# Generated by Django 3.1.7 on 2021-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='avgSpeed',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='enStatus',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='flLevel',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='speed',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='temperature',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
