# Generated by Django 3.1.7 on 2021-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20211030_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='enStatus',
            field=models.CharField(choices=[('y', 'Working'), ('n', 'Not working')], max_length=50),
        ),
    ]
