# Generated by Django 3.1.7 on 2021-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20211030_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='flLevel',
            field=models.CharField(max_length=50),
        ),
    ]
