# Generated by Django 3.1.7 on 2021-11-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20211030_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='enStatus',
            field=models.CharField(choices=[('Working', 'Working'), ('Not working', 'Not working')], max_length=50),
        ),
    ]
