# Generated by Django 3.1.7 on 2021-11-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20211101_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='enStatus',
            field=models.CharField(choices=[('W', 'Working'), ('NW', 'Not working')], max_length=50),
        ),
    ]
