# Generated by Django 3.1.7 on 2021-11-01 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20211101_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='flLevel',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
