# Generated by Django 3.1.7 on 2021-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20211101_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='flLevel',
            field=models.CharField(max_length=50),
        ),
    ]
